### ISSUE TITLE
Border if tabs > 1

### ISSUE THREAD

**Issue by whoizit** [tsloughter/tilda#7]
Please delete the border that appears when the tabs > 1

**Comment by lanoxx** [comment]
Hi, i see what you mean. I will take a look at it later today. In the mean time, there is a new version which you can find at https://github.com/lanoxx/tilda which is going to be released soon. Feel free to test it and report bugs if you like.

**Comment by lanoxx** [comment]
This is fixed in the master branch at https://github.com/lanoxx/tilda.

**Comment by whoizit** [comment]
this is not work for me. I'm remove config dirs. ~/.tilda & ~/.config/tilda

This is stil showing border, I dont see this options in preferences. This is breake hotkeys "Go To Next Tab", "Go to Previous Tab", work now only as "Go To Last Tab", "Go to First Tab". This is breake scroll bar. Its incorrect and ugly now. Tnx.

**Comment by lanoxx** [comment]
Thanks, i will take a look.

**Comment by lanoxx** [comment]
The option is in Preferences->General->Show Notebook Border if you remove the tick, then it should not display a border. If it does not work for you, then it might be a problem with your theme. Could you tell me which theme you are running?

I have just pushed a fix for the next/prev issue, could you give it a try and tell me if it works for you now?

**Comment by lanoxx** [comment]
Btw. tilda should automatically migrate the config files from ~/.tilda to ~/.config/tilda, so you dont ened to delete the files.

**Comment by whoizit** [comment]
Border still appears. Nothing has changed. Tabs looking ugly and not useful. Scroll bar still breaks.

**Comment by lanoxx** [comment]
I just committed a new patch to https://github.com/lanoxx/tilda (master) which should fix the scrollbar, could you post a screen shot of the tabs, I'm not sure what you mean with ugly?

**Comment by lanoxx** [comment]
I have uploaded another fix for the border issue, could you check if it looks better now? Unfortunately that is not so easy to fix, since there is a related bug inside gtk+: https://bugzilla.gnome.org/process_bug.cgi

**Comment by whoizit** [comment]
Now I see border only on top http://fastpic.ru/view/41/2012/0917/e344cbfc8d7bf640605ac7021aad2980.png.html
Ugly mean what I don't know on which tab located. 

See as it works on 'Guake' http://fastpic.ru/view/43/2012/0917/34da30747120277cc621dc90b7bfea6b.png.html

**Comment by lanoxx** [comment]
atommixz, I believe it is a problem with your theme, not with tilda, but im not sure. AFAIK guake is still using gtk2, while tilda is now using gtk3. Can you check if you have a proper gtk3 theme installed? Also what kind of window manager are you using?

If your desktop environment is still based on gtk2, then you might want to checkout http://shimmerproject.org/project/greybird/

**Comment by whoizit** [comment]
Yes, it's trouble gtk-3 theme.

Btw, https://gist.github.com/3765347

Btw, tabs added on first, but not on last position.

**Comment by lanoxx** [comment]
Thanks for the reply. Yes, that patch would fix it on, but then also the tabs have a wrong padding. I think the best solution is to load the CSS from an external file, and then you and other people can customize it according to their needs. Because it seems that every theme needs a bit different adjustments. For example on the Gnome default theme (Adwaita) the padding is already set to zero, so I don't need to change anything, but on the Ubuntu themes Ambiance or Radiance I need to set the padding to zero.

I will look at the tab adding code and change it to add them at the last position

**Comment by lanoxx** [comment]
The tab adding is fixed in master

**Comment by whoizit** [comment]
forgot about the patch?

**Comment by lanoxx** [comment]
Hi, sorry it took me a little longer. I have just uploaded a fix, that allows you to define a custom css file in the tilda config directory. Just create a file named "style.css" in ~/.config/tilda/ and put your required css inside it. I have removed most of the build in css now, because there is no way to make it work reliably on all kinds of installed themes. In your case you can put in something like:

``` css
.notebook {
    padding: 0px;
}
```

**Comment by lanoxx** [comment]
I'm gonna close this issue. Please reopen if you still have problems.

**Comment by ntrp** [comment]
Hi, I am using tilda latest version from git and I can't manage to remove that damn border... I tried adding the style.css and I also tried this solution:

http://askubuntu.com/questions/221291/remove-ugly-fat-bazel-from-gnome-terminal-with-multiple-tabs

but nothing seems to remove it or has any effect on it.

My configuration:
Arch Linux
Openbox
Ambiance GTK3 theme

What am I doing wrong or am I missing? Anyway great terminal! The latest version is amazing.. I wonder why it isn't already in the repositories.

**Comment by lanoxx** [comment]
Just to make sure, did you use the latest code from lanoxx/tilda-1-0 or from this repository (tsloughter/master)? The latest version is 1.0.x from lanoxx/. Given that this does not work, I would assume that you are probably using the version from this repository which still uses GTK-2 instead of GTK-3 and which also does not know about style.css.

Anyway if you are running that version and it still does not remove the border (which actually is a padding) around the window, then you can try to change to another theme and check if its still the same there. For Gnome there is a Default Theme (Adwaita) that does not come with a border, but I do not know about Openbox.

Please reply with the version you are using and if there really is a bug then I will be happy to fix it.

**Comment by lanoxx** [comment]
P.S The main reason tilda is not in any repository is because I could not find any maintainer for it (although I mainly contacted people at Ubuntu and Debian) and I do not have any packaging experience myself. Feel free to convince someone at Arch Linux to pull from my repository.

**Comment by ntrp** [comment]
Ah ok, I compiled from this one. As soon as I get some free time I will try the new version. I will see if I can do something about the repository too :)

**Comment by ntrp** [comment]
Ok in the new 1.0 version it works very well. Is there a way to change the tab spacing? I tried adding margin but it isn't working..

p.s. I forked your repo and I added a little feature: Now the two windows (tilda_window and wizard) have names so I can use CSS only on one and not mess up the other. Look at the effect, it's very nice :D.

![2013-01-23-234122_1366x768_scrot](https://f.cloud.github.com/assets/720492/91791/a8b61f3e-65ae-11e2-9ee4-875787572b41.png)

**Comment by lanoxx** [comment]
That looks nice, if you could change your commit in such a way,  that it does not include any of i18n line changes, the I will be happy to pull from you.

P. S. what desktop are you using? Is that openbox?

**Comment by ntrp** [comment]
Yeah, I have seen that it committed the i18n stuff too but I have no time to fix it now.. should I add it to .gitignore or are you using another method to not commit that stuff (I am using the standard make && make install chain)? I will fix that as soon as I get some more time to work on it.

About the desktop my setup is:
OpenBox (Compton)
tint2
conky
Ambiance GTK theme
Faenza Icon theme

**Comment by tsloughter** [comment]
And send changes this way, too! :)

**Comment by ntrp** [comment]
I modified the commit, now it includes only the two line of modifications in tilda.c and window.c. How do I send changes? Never done any work on forked repositories before..

**Comment by whoizit** [comment]
You need create Pull Request. I think.

**Comment by whoizit** [comment]
Or lanoxx do it himself, maybe

**Comment by ntrp** [comment]
Hum I think they need to pull request me

**Comment by lanoxx** [comment]
ntrp, very nice. Just click "Pull Requst" and I will merge it.

Regarading the po files, since they are updated automatically by the i18n tools I don't want to have them mess up the commit history everytime there are small changes, I guess its enough to only commit them when there are actually translation or string changes.

**Comment by whoizit** [comment]
Very useful for me right now. My style.css, If someone need https://gist.github.com/4620124

**Comment by whoizit** [comment]
Tnx a lot
